### ISSUE TITLE
I get window undefined error when using web3react demo on nextjs app

### ISSUE THREAD

**Issue by petermunachi** [StardustCollective/stargazer-wallet-demos#3]
I get this error when I use the stargazer web3react connector
#ReferenceError: window is not defined
    at new StargazerConnector (/home/node_modules/@stardust-collective/web3-react-stargazer-connector/dist/cjs/connector.js:32:9)
    at eval (webpack-internal:///./connectors/stargazer.ts:8:28)
    at Object../connectors/stargazer.ts (/home/.next/server/pages/_app.js:660:1)
    at __webpack_require__ (/home/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./utils/getWalletProviders.tsx:16:79)
    at Object../utils/getWalletProviders.tsx (/home/.next/server/pages/_app.js:1563:1)
    at __webpack_require__ (/home/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/layouts/GlobalLayout/Navbar/Profile/ProfileWalletConnection.tsx:11:82)
    at Function.__webpack_require__.a (/home/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./components/layouts/GlobalLayout/Navbar/Profile/ProfileWalletConnection.tsx:1:21) {
  page: '/'
}

This is how I declare the connector
#import { StargazerConnector } from '@stardust-collective/web3-react-stargazer-connector';

declare global {
  interface Window {
    stargazerConnector: StargazerConnector;
  }
}

const stargazerConnector = new StargazerConnector({
  supportedChainIds: [1, 3]
});

window.stargazerConnector = stargazerConnector;

export { stargazerConnector };

**Comment by juandavidkincaid** [comment]
What platform are you using?, the `window` object should be available in most contexts

**Comment by AlexBrandes** [comment]
@petermunachi Since NextJS runs code on both the front end and back end, you may need to ensure that the StargazerConnector is only running on the front end code. 

This StackOverflow answer might help:
https://stackoverflow.com/questions/55151041/window-is-not-defined-in-next-js-react-app
